version: "3"
services:

  dbuser:
    image: mysql:8.0
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/local/mysql/data
    ports:
      - "3307:3306"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=qwertyui
      - MYSQL_DATABASE=user_service
    networks:
      - app-networks

  maven-app:
    build: 
      context: ./user-service
      dockerfile: ./Dockerfile
    container_name: user-service
    hostname: maven-app
    tty: true
    ports:
      - "8888:8888"
    depends_on:
      - dbuser
    networks:
      - app-networks
  
networks:
  app-networks:
    driver: bridge
   

volumes:
  mysql-data:
    driver: local
