version: "3.8"
services:

#user service
  dbuser:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwertyui
      MYSQL_DATABASE: user_service
    networks:
      - app-networks

  user-service-app:
    build:
      context: ./user-service
      dockerfile: ./Dockerfile
    container_name: user-service
    ports:
      - "8888:8888"
    depends_on:
      - dbuser
    networks:
      - app-networks

#shop service
  dbshop:
    image: mysql:8.0
    container_name: dbshop
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwertyui
      MYSQL_DATABASE: shop_service
    networks:
      - app-networks

  shop-service-app:
    build:
      context: ./shop-service
      dockerfile: ./Dockerfile
    container_name: shop-service
    ports:
      - "8887:8887"
    depends_on:
      - dbshop
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge

