name: Java CI CD PLEASE WOR

on:
  push:
    branches:
      - main


env:
  PROJECT_ID: market2door
  SERVICE: webapp
  REGION: europe-west4 # Add a service name here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build User Microservice
        run: mvn clean package -DskipTests
        working-directory: ./user-service

      - name: Create target directory
        run: mkdir -p target

      - name: List contents of staging directory
        run: ls -la user-service/staging

      - name: Move JAR files to target directory
        run: mv user-service/staging/*.jar target/
        if: success() # Only move if previous steps were successful

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: userservice-jar
          path: |
            target/*.jar
            target/*.original.jar
