name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Build User Microservice
        working-directory: ./user-service
        run: mvn --batch-mode package -DskipTests
      
      - name: Build Shop Microservice
        working-directory: ./shop-service
        run: mvn --batch-mode package -DskipTests

      - name: Build Cart Microservice
        working-directory: ./cart-service
        run: mvn --batch-mode package -DskipTests

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group Market2DoorResources --name Market2DoorCluster

      - name: Deploy User Microservice
        run: |
          kubectl apply -f ./user-service-deployment.yml
          kubectl apply -f ./user-service.yml
