name: FrontEnd - CI CD

on:
  push:
    paths:
      - 'discovery-service/**'
    branches:
      - main

env:
  PROJECT_ID: market2door-426707
  SERVICE: frontend-service
  REGION: europe-west4
  PORT: 3000      
            
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: frontEnd
        run: npm install

      - name: Build the project
        working-directory: frontEnd
        run: npm run build

  e2e-test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies and build the project
      - name: Install and build frontend
        working-directory: frontEnd
        run: |
          npm install
          npm run build

      # Start the frontend application
      - name: Start frontend
        working-directory: frontEnd
        run: npm start &

      # Install Cypress dependencies
      - name: Install Cypress dependencies
        working-directory: frontEnd
        run: npm install cypress

      # Run Cypress tests
      - name: Run Cypress tests
        working-directory: frontEnd
        run: npx cypress run --spec "cypress/e2e/spec.cy.ts"

  deploy:
    runs-on: ubuntu-latest
    needs: e2e-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Sets up the gcloud cli with the credentials we previously created, and will be storing within Github as secrets.
      - name: Setup Cloud cli
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GC_SE_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t gcr.io/market2door-426707/${{ env.SERVICE }}:${{ github.sha }} -f ./frontEnd/Dockerfile ./frontEnd
      
      - name: Push Docker image to Container Registry
        run: docker push gcr.io/market2door-426707/${{ env.SERVICE }}:${{ github.sha }}

      - name: Show Output
        run: echo ${{ steps.gohibeesh.outputs.url }}

      - name: Deploy to Cloud Run
        id: gohibeesh
        run: gcloud run deploy ${{env.SERVICE}} --image gcr.io/market2door-426707/${{ env.SERVICE }}:${{ github.sha }} --platform managed --region ${{env.REGION}} --allow-unauthenticated --min-instances 1

  
