name: security-ci-cd

on:
  push:
    paths:
      - 'SpringSecurityJWT/**'
    branches:
      - main

env:
  PROJECT_ID: market2door-426707
  SERVICE: spring-security-service
  REGION: us-central1
  PORT: 6060
  MAX_INSTANCES: 10  # Set your desired maximum number of instances here
  CPU: 5  # Adjusted maximum CPU allocation (in vCPU)
  MEMORY: 2Gi  # Set maximum memory allocation

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Build Security Microservice
        working-directory: ./SpringSecurityJWT
        run: mvn --batch-mode package -DskipTests
        env:
          DB_USER: ${{ secrets.User_DB_USER }}
          DB_PASSWORD: ${{ secrets.User_DB_PASSWORD }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: "${{ github.workspace }}/SpringSecurityJWT/target/*.jar"
      
# Deploy Google Cloud Run
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GC_SE_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t gcr.io/market2door-426707/${{ env.SERVICE }}:${{ github.sha }} -f ./SpringSecurityJWT/Dockerfile ./SpringSecurityJWT
      
      - name: Push Docker image to Container Registry
        run: docker push gcr.io/market2door-426707/${{ env.SERVICE }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        id: deploy_cloud_run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image gcr.io/market2door-426707/${{ env.SERVICE }}:${{ github.sha }} \
            --port ${{ env.PORT }} \
            --region ${{ env.REGION }} \
            --max-instances ${{ env.MAX_INSTANCES }} \
            --cpu ${{ env.CPU }} \
            --memory ${{ env.MEMORY }} \
            --allow-unauthenticated || true
